import { Inter } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aung Myo Myat",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params: {locale}}) {

    const loadMessages = async () => {
        let messages;
        try {
            messages = (await import(`../../../messages/${locale}.json`)).default;
        } catch (error) {
            console.log(error)
        }
        return messages;
    }

    return (
        <html lang={locale} className={'!scroll-smooth'}>
        <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={await loadMessages()}>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
